'use strict';
const A=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const base='app/src/main/assets/';
const dom=new JSDOM('<!doctype html><html><body><div id="arqueLab"></div></body></html>',{
 url:'https://arque.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,doc=w.document;
for(const name of ['modules.js','kitchen-catalog.js','lab-alignment.js','lab-advanced.js','lab-visual.js','workshop.js','module-ui.js','lab.js'])
 w.eval(fs.readFileSync(base+name,'utf8'));
const M=w.ArqueModules;
const first=M.instantiate({id:'one',spec:M.standard()},1050,100),second=M.instantiate({id:'two',spec:M.standard()},110,1200);
first.z=100;second.z=100;
const stroke={id:'stroke',kind:'pen',view:'plan',label:'Parede S Pen',points:[[50,50],[1250,53],[1250,700]],x:50,y:50,w:1200,d:650,height:0};
const l={width:3800,depth:2800,height:2600,confirmed:true,roomRefs:{},items:[first,second,stroke],history:[],future:[],photoId:''};
const p={rooms:[{id:'room',name:'Cozinha L',measurements:[]}],labLayouts:{room:l},photos:[]},state={moduleTemplates:[],profileTemplates:[]},toasts=[];
w.ArqueLab.mount(p,{state,persist:()=>Promise.resolve(),toast:m=>toasts.push(m),exportCutMaterial:()=>{}});
const action=(id,arg)=>{const el=[...doc.querySelectorAll('[data-lab="'+id+'"]')].find(i=>arg===undefined||i.dataset.arg===arg);A(el,'Ação '+id+' ausente');el.click();};
const input=(id,value)=>{const el=doc.getElementById(id);A(el,id+' ausente');el.value=value;};
A(doc.body.textContent.includes('Oficina Arque'),'seis ferramentas presentes no primeiro acesso');
for(const name of ['advCorner','advCava','advMagnet','advExportCsv','advTraceWalls'])A(doc.querySelector('[data-lab="'+name+'"]'),'comando '+name);
input('advCornerBack',first.id);input('advCornerSide',second.id);
input('advCornerGap','30');action('advCorner');
A.equal(second.rotation,90,'parede lateral rotacionada em 90 graus');
A.equal(first.x,first.moduleSpec.depth+first.moduleSpec.backThickness+30);
A.equal(first.y,0);
input('advCavaOrigin',first.id);input('advCavaTarget',second.id);
input('advCavaLevel','680');action('advCava');
A(first.moduleSpec.cavaProfile&&second.moduleSpec.cavaProfile);
A.equal(first.moduleSpec.cavaProfile.levelZ,680);
A(M.parts(first.moduleSpec).parts.some(x=>x.name.includes('Régua cava alinhada')));
const originalSvg=doc.querySelector('#labBoard').outerHTML;
A(originalSvg.includes('stroke-dasharray="9 3"'),'linha de cava desenhada na vista espacial');
action('advMagnet');A(doc.body.textContent.includes('Ímã desligado'));
action('advMagnet');A(doc.body.textContent.includes('Ímã ativo'));
const choose=(id)=>{
 const g=doc.querySelector('#labBoard [data-lab-object="'+id+'"]');A(g);
 const event=new w.Event('pointerdown',{bubbles:true,cancelable:true});
 Object.defineProperties(event,{pointerId:{value:11},isPrimary:{value:true},clientX:{value:220},clientY:{value:240}});
 g.dispatchEvent(event);
};
choose(first.id);
const partBtn=[...doc.querySelectorAll('[data-lab="partSelect"]')].find(el=>el.dataset.arg.startsWith('extra-'));
A(partBtn,'régua listada na árvore de peças');partBtn.click();
A(doc.querySelector('#advPartHeight'),'peça adicional editável');
input('advPartHeight','60');
action('advEditPart');A(first.moduleSpec.assemblyPieces.some(x=>x.type==='cavaRail'&&x.height===60));
A(doc.body.textContent.includes('Marcar conferência do módulo'));
action('advApprove');A.equal(first.productionApproval,true);
action('view','plan');
A(doc.querySelector('#labBoard').getAttribute('aria-label').includes('Planta'));
action('advTraceWalls');
A.equal(l.wallTrace.segments.length,2);
A.equal(l.wallTrace.verified,false);
A(doc.querySelector('#labBoard').outerHTML.includes('#a06838'),'paredes traçadas aparecem na planta');
A(l.history.length>4,'operações têm histórico de desfazer');
const report=w.ArqueAdvanced.production(l,M);
A(report.lines.some(x=>x.code.includes('-P')));
A.equal(report.ready,false,'dados não liberados para CNC sem aprovação técnica');
const csv=w.ArqueAdvanced.csv(report);
A(csv.includes('M01-P01'));
console.log('Interface avançada: 6 recursos integrados, canto L, cava, peças, ímã, paredes e relatório OK.');
