'use strict';
const assert=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js');
const A=require('../app/src/main/assets/lab-advanced.js');
globalThis.ArqueModules=M;
const create=(label,x,y,z=100)=>{const o=M.instantiate({id:label,spec:M.standard()},x,y);o.z=z;o.code=label;return o;};
const back=create('M01',1200,100),left=create('M02',100,700),third=create('M03',2500,1300);
const layout={width:4000,depth:3000,height:2700,confirmed:true,items:[back,left,third]};
const corner=A.kitchenCorner(layout,back.id,left.id,{clearance:35,wallGap:10});
assert.equal(corner.changes.length,2);
const movedLeft=corner.changes.find(x=>x.id===left.id),movedBack=corner.changes.find(x=>x.id===back.id);
assert.equal(movedLeft.rotation,90);
assert.equal(movedBack.x,10+A.dims({...left,rotation:90}).w+35);
assert.equal(movedBack.y,10);
assert.deepEqual(layout.items.map(x=>x.rotation),[undefined,undefined,undefined],'pré-visualização não altera modelos');
assert.throws(()=>A.kitchenCorner({...layout,width:1000},back.id,left.id,{}),/cabem/);
const snapRoom={...layout,items:[back,left]};const near=A.magnetic(snapRoom,left.id,back.x+back.w+18,back.y,45);
assert.equal(near.snapped,true);
assert.equal(near.x,back.x+back.w);
assert.equal(near.y,back.y);
const noSnap=A.magnetic(snapRoom,left.id,500,1800,20);
assert.equal(noSnap.snapped,false);
assert.throws(()=>A.magnetic(snapRoom,left.id,4000,300,30),/Não há posição livre/);
const cava=A.cavaAlign(layout,back.id,[left.id],{levelZ:680,railHeight:70,clearance:3},M);
assert.equal(cava.changes.length,2);
for(const item of cava.changes){
 assert.equal(item.spec.frontType,'cava');
 assert.equal(item.spec.cavaProfile.levelZ,680);
 assert.equal(item.spec.assemblyPieces.some(p=>p.type==='cavaRail'),true);
 assert(M.parts(item.spec).parts.some(p=>p.name.includes('Régua cava alinhada')));
}
assert.throws(()=>A.cavaAlign(layout,back.id,[left.id],{levelZ:200},M),/fora da carcaça/);
const s=cava.changes[0].spec;
const part=s.assemblyPieces.find(x=>x.type==='cavaRail');
const edited=A.editPart(s,part.id,{height:60,at:55,widthClearance:4},M);
assert.equal(edited.assemblyPieces.find(x=>x.id===part.id).height,60);
assert.equal(edited.assemblyPieces.find(x=>x.id===part.id).widthClearance,4);
assert.equal(s.assemblyPieces.find(x=>x.id===part.id).height,70,'edição não altera modelo anterior');
assert.throws(()=>A.editPart(s,'nao-existe',{height:80},M),/Selecione/);
const stroke={id:'w1',kind:'pen',view:'plan',points:[[0,0],[1000,5],[1000,800],[2000,802]]};
const traced=A.traceWalls({width:3000,depth:2500,items:[stroke]},[],30);
assert.equal(traced.segments.length,3);
assert.equal(traced.verified,false);
assert.equal(traced.segments[0].length,1000);
assert.throws(()=>A.traceWalls({width:3000,depth:2500,items:[{...stroke,points:[[0,0],[600,400]]}]},[],30),/Linha diagonal/);
const moduleOk=create('M12',100,100);
moduleOk.moduleSpec.frontType='sem';
moduleOk.productionApproval=true;
const production=A.production({width:3000,depth:2500,height:2600,confirmed:true,items:[moduleOk]},M);
assert(production.lines.length>3);
assert(production.lines.every(p=>p.code.startsWith('M12-P')));
assert(production.warnings.some(w=>w.includes('dobradiças')));
assert.equal(production.ready,false,'sem furação e conferência não liberar produção');
const rows=A.csv(production);
assert(rows.startsWith('\ufeffcode;module;name;'));
assert(rows.includes('M12-P01'));
assert(!A.production({...layout,confirmed:false},M).ready);
console.log('Oficina avançada: canto 90, ímã, cava, peça, paredes e produção OK.');
