'use strict';
const assert=require('node:assert/strict'),A=require('../app/src/main/assets/agenda.js');
const first=A.validate({id:'delivery',title:'Entrega cozinha',type:'Entrega',startAt:'2030-05-12T09:00',endAt:'2030-05-12T11:00',reminderMinutes:60,projectId:'obra-1',notes:'Conferir ferragens',status:'Pendente'},[]);
assert.equal(first.title,'Entrega cozinha');
assert.equal(first.projectId,'obra-1');
assert.equal(first.reminderMinutes,60);
assert.throws(()=>A.validate({...first,title:''},[]),/título/);
assert.throws(()=>A.validate({...first,endAt:'2030-05-12T08:00'},[]),/posterior/);
assert.throws(()=>A.validate({...first,reminderMinutes:999},[]),/Antecedência/);
assert.throws(()=>A.validate({...first,id:'other',startAt:'2030-05-12T10:30',endAt:'2030-05-12T12:00'},[first]),/Horário ocupado/);
const adjacent=A.validate({...first,id:'next',startAt:'2030-05-12T11:00',endAt:'2030-05-12T12:00'},[first]);
assert.equal(A.conflicts([first],adjacent).length,0);
const free=A.freeSlots([first,adjacent],'2030-05-12');
assert.equal(free.length,2);
assert.equal(new Date(free[0].start).getHours(),8);
assert.equal(new Date(free[0].end).getHours(),9);
assert.equal(new Date(free[1].start).getHours(),12);
assert.equal(new Date(free[1].end).getHours(),19);
assert.equal(A.dayEvents([first,adjacent],'2030-05-12').length,2);
assert.equal(A.dayEvents([first,adjacent],'2030-05-13').length,0);
assert.equal(A.nativeReminders([first,{...adjacent,status:'Concluído'}],new Date('2029-06-01T10:00').getTime()).length,1);
const crossing=A.validate({...first,id:'overnight',startAt:'2030-05-12T23:30',endAt:'2030-05-13T01:00'},[]);
assert.equal(A.dayEvents([crossing],'2030-05-13').length,1,'evento que cruza meia-noite aparece no dia seguinte');
const canceled={...first,status:'Cancelado'};
assert.equal(A.freeSlots([canceled],'2030-05-12').length,1,'cancelado libera o horário');
const editing=A.validate({...first,title:'Entrega remarcada'},[first]);
assert.equal(editing.title,'Entrega remarcada','edita sem conflito consigo mesmo');

const obra={id:'obra-carpintaria',clientId:'c1',name:'Cozinha planejada',address:'Rua das Flores, 100',status:'Aprovado',
 deliveryDate:'2030-05-12',deliveryTime:'13:00',deliveryDurationMinutes:120};
assert.throws(()=>A.syncProjectDelivery([],{...obra,deliveryDate:''},'Cliente Maria'),/data e o horário/);
assert.throws(()=>A.syncProjectDelivery([],{...obra,deliveryTime:''},'Cliente Maria'),/data e o horário/);
assert.throws(()=>A.syncProjectDelivery([],{...obra,deliveryDate:'2030-02-31'},'Cliente Maria'),/inválidos/);
assert.throws(()=>A.syncProjectDelivery([first],{...obra,deliveryTime:'10:00'},'Cliente Maria'),/Horário ocupado/);
const linked=A.syncProjectDelivery([first],obra,'Cliente Maria');
assert.equal(linked.length,2,'cria exatamente uma entrega sem remover compromisso manual');
const assigned=linked.find(x=>x.source==='project-delivery');
assert(assigned,'evento automático marcado como pertencente à obra');
assert.equal(assigned.projectId,obra.id);
assert.equal(assigned.startAt,'2030-05-12T13:00');
assert.equal(assigned.endAt,'2030-05-12T15:00');
assert(assigned.title.includes('Cliente Maria'));
assert.equal(A.nativeReminders(linked,new Date('2029-06-01T09:00').getTime()).length,2,'entrega aparece nas notificações');
const same=A.syncProjectDelivery(linked,{...obra,status:'Produção'},'Cliente Maria');
assert.equal(same.length,2,'passar a Produção não duplica entrega');
assert.equal(same.find(x=>x.source==='project-delivery').id,assigned.id);
const rescheduled=A.syncProjectDelivery(same,{...obra,status:'Produção',deliveryDate:'2030-05-13',deliveryTime:'14:30',deliveryDurationMinutes:60},'Cliente Maria');
assert.equal(rescheduled.length,2,'remarcação não duplica');
assert.equal(rescheduled.find(x=>x.source==='project-delivery').id,assigned.id,'remarcação conserva ID da notificação');
assert.equal(rescheduled.find(x=>x.source==='project-delivery').startAt,'2030-05-13T14:30');
assert.equal(rescheduled.find(x=>x.source==='project-delivery').endAt,'2030-05-13T15:30');
assert.equal(A.dayEvents(rescheduled,'2030-05-12').length,1,'entrega não ocupa mais dia antigo');
assert.equal(A.dayEvents(rescheduled,'2030-05-13').length,1,'entrega aparece no dia novo');
const mounted=A.syncProjectDelivery(rescheduled,{...obra,status:'Montagem',deliveryDate:'2030-05-13',deliveryTime:'14:30',deliveryDurationMinutes:60},'Cliente Maria');
assert.equal(mounted.find(x=>x.source==='project-delivery').status,'Pendente','montagem não apaga entrega');
const finished=A.syncProjectDelivery(mounted,{...obra,status:'Finalizado'},'Cliente Maria');
assert.equal(finished.find(x=>x.source==='project-delivery').status,'Concluído','finalizar obra encerra aviso');
assert.equal(A.nativeReminders(finished,new Date('2029-06-01').getTime()).length,1,'concluído não notifica');
const deliveryCanceled=A.syncProjectDelivery(mounted,{...obra,status:'Cancelado'},'Cliente Maria');
assert.equal(deliveryCanceled.find(x=>x.source==='project-delivery').status,'Cancelado');
const reactivated=A.syncProjectDelivery(deliveryCanceled,{...obra,status:'Aprovado'},'Cliente Maria');
assert.equal(reactivated.find(x=>x.source==='project-delivery').id,assigned.id,'reativar não cria segundo registro');

console.log('AGENDA: agendamento, conflito, horários livres, edição, avisos e virada de dia OK.');
