'use strict';
const assert=require('node:assert/strict'),A=require('../app/src/main/assets/agenda.js');
const first=A.validate({id:'delivery',title:'Entrega cozinha',type:'Entrega',startAt:'2030-05-12T09:00',endAt:'2030-05-12T11:00',reminderMinutes:60,projectId:'obra-1',notes:'Conferir ferragens',status:'Pendente'},[]);
assert.equal(first.title,'Entrega cozinha');
assert.equal(first.projectId,'obra-1');
assert.equal(first.reminderMinutes,60);
assert.throws(()=>A.validate({...first,title:''},[]),/título/);
assert.throws(()=>A.validate({...first,endAt:'2030-05-12T08:00'},[]),/posterior/);
assert.throws(()=>A.validate({...first,reminderMinutes:999},[]),/Antecedência/);
assert.throws(()=>A.validate({...first,id:'other',startAt:'2030-05-12T10:30',endAt:'2030-05-12T12:00'},[first]),/Horário ocupado/);
const adjacent=A.validate({...first,id:'next',startAt:'2030-05-12T11:00',endAt:'2030-05-12T12:00'},[first]);
assert.equal(A.conflicts([first],adjacent).length,0);
const free=A.freeSlots([first,adjacent],'2030-05-12');
assert.equal(free.length,2);
assert.equal(new Date(free[0].start).getHours(),8);
assert.equal(new Date(free[0].end).getHours(),9);
assert.equal(new Date(free[1].start).getHours(),12);
assert.equal(new Date(free[1].end).getHours(),19);
assert.equal(A.dayEvents([first,adjacent],'2030-05-12').length,2);
assert.equal(A.dayEvents([first,adjacent],'2030-05-13').length,0);
assert.equal(A.nativeReminders([first,{...adjacent,status:'Concluído'}],new Date('2029-06-01T10:00').getTime()).length,1);
const crossing=A.validate({...first,id:'overnight',startAt:'2030-05-12T23:30',endAt:'2030-05-13T01:00'},[]);
assert.equal(A.dayEvents([crossing],'2030-05-13').length,1,'evento que cruza meia-noite aparece no dia seguinte');
const canceled={...first,status:'Cancelado'};
assert.equal(A.freeSlots([canceled],'2030-05-12').length,1,'cancelado libera o horário');
const editing=A.validate({...first,title:'Entrega remarcada'},[first]);
assert.equal(editing.title,'Entrega remarcada','edita sem conflito consigo mesmo');
console.log('AGENDA: agendamento, conflito, horários livres, edição, avisos e virada de dia OK.');
