'use strict';
const A=require('node:assert/strict'),Align=require('../app/src/main/assets/lab-alignment.js'),Lab=require('../app/src/main/assets/lab.js'),Mods=require('../app/src/main/assets/modules.js');
const room={width:3600,depth:3000,height:2600,confirmed:true,items:[]};
const stone={id:'stone',kind:'countertop',label:'Pedra',x:100,y:100,z:865,w:1800,d:600,height:35};
const cooker={id:'cook',kind:'appliance',type:'cooktop',label:'Cooktop',x:150,y:150,z:700,w:600,d:510,height:45};
const oven={id:'oven',kind:'appliance',type:'oven',label:'Forno',x:200,y:200,z:100,w:540,d:480,height:520};
const mod={...Mods.instantiate({id:'m',spec:Mods.standard()},100,100),z:100};
const mod2={...Mods.instantiate({id:'m2',spec:Mods.standard()},1400,150),z:100};
room.items.push(stone,cooker,oven,mod,mod2);
const before=JSON.stringify(room);
const cp=Align.center(room,'cook','stone','cooktop',20);
A.equal(cp.x,700);A.equal(cp.y,145);A.equal(cp.z,900);
A.equal(cp.alignment.targetId,'stone');A.equal(cp.alignment.mode,'cooktop');
A.equal(JSON.stringify(room),before,'alinhar não altera móveis antes de confirmar');
A.equal(Align.center(room,'cook','stone','both',0).x,700);
A.equal(Align.center(room,'oven','stone','left',0).x,100);
A.equal(Align.center(room,'oven','stone','right',0).x,1360);
A.equal(Align.center(room,'oven','stone','front',0).y,220);
A.equal(Align.center(room,'oven','stone','back',0).y,100);
A.throws(()=>Align.center(room,'oven','stone','cooktop'),/cooktop/);
A.throws(()=>Align.center(room,'cook','oven','both'),/bancada ou móvel/);
A.throws(()=>Align.center(room,'cook','stone','cooktop',60),/não cabe/);
A.throws(()=>Align.center(room,'cook','missing','both'),/Selecione/);
const wLeft=Align.alongWall(room,mod.id,'left',30);
A.equal(wLeft.rotation,90);A.equal(wLeft.x,30);
const wRight=Align.alongWall(room,mod.id,'right',0);
A.equal(wRight.rotation,270);A.equal(wRight.x,3600-560);
A.equal(Align.alongWall(room,mod.id,'back').y,0);
A.equal(Align.alongWall(room,mod.id,'front').y,3000-560);
A.equal(Align.beside(room,mod2.id,mod.id,'right',10).x,910);
A.equal(Align.beside(room,mod2.id,mod.id,'right',10).y,100);
A.equal(Align.beside(room,mod2.id,mod.id,'frontFlush',0).y,100);
A.throws(()=>Align.beside(room,mod2.id,mod.id,'nonsense'),/inválido/);
const linked={...cooker,...cp};
room.items[1]=linked;
room.items[0]={...stone,w:2000};
const updates=Align.reapply(room,'stone');A.equal(updates.length,1);A.equal(updates[0].next.x,800);
A.equal(linked.x,cp.x,'re-alinhamento retorna mudanças sem escrever');
A.throws(()=>Align.center({...room,width:900},'cook','stone','cooktop',0),/limites/);
const trace={id:'trace',kind:'pen',view:'plan',points:[[100,100],[250,107],[400,91],[600,101],[850,104]]};
const second={id:'next',kind:'pen',view:'plan',points:[[886,126],[945,181],[1060,200],[1180,203]]};
const wrongView={id:'front',kind:'pen',view:'front',points:[[845,105],[925,105]]};
const geometry={width:2500,depth:2000,items:[trace,second,wrongView],confirmed:true};
const result=Align.automaticSketch(geometry,'',{tolerance:80,smoothness:30},'plan');
A.equal(result.count,2,'corrigir apenas planta');
A(result.connected>0,'unir extremidades próximas');
const a=result.updates.find(x=>x.id==='trace'),b=result.updates.find(x=>x.id==='next');
A.equal(a.points.length,2,'rabisco torto transformado em reta');
A.deepEqual(a.points[1],b.points[0],'conexão entre pontas de linhas próximas');
A.equal(result.updates.some(x=>x.id==='front'),false,'nunca conecta planta à elevação');
const only=Align.automaticSketch(geometry,'trace',{tolerance:80,smoothness:30},'plan');
A.equal(only.updates.length,1);
A.deepEqual(trace.points,[[100,100],[250,107],[400,91],[600,101],[850,104]],'esboço original só muda após confirmação');
A.throws(()=>Align.automaticSketch({items:[]},'',{},'plan'),/Desenhe/);
A.throws(()=>Align.automaticSketch(geometry,'',{tolerance:501},'plan'),/deve estar/);
A.deepEqual(Align.orthogonal([[20,20],[500,46]],80),[[20,20],[500,20]],'linha quase horizontal vira horizontal');
const badPts=[{id:'line',kind:'pen',view:'plan',points:[[10,10],[11,12]]}];
A.throws(()=>Align.automaticSketch({items:badPts},'',{},'plan'),/longos/);
console.log('Arque Align: cooktop, centralização, paredes, módulos e esboços conectados OK.');
