/* Oficina por vao: painel real em mm, armazenamento, redimensionamento e ferragens. */
'use strict';
const assert=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js');
const find=(result,key)=>result.parts.find(p=>p.key===key);
const old=M.standard();
const snapshot=JSON.stringify(old);
const rail=M.insertAssembly(old,'rail',0,{at:0.7,height:70,widthClearance:3,frontInset:0});
assert.equal(rail.assemblyPieces.length,1);
const id=rail.assemblyPieces[0].id;
assert(/^[A-Za-z0-9_-]+$/.test(id));
const part=find(M.parts(rail),'extra-'+id);
assert.equal(part.w,758);
assert.equal(part.h,70);
assert.equal(part.qty,1);
assert.equal(part.material,'MDF 18 mm');
assert(!M.parts(rail).parts.some(p=>p.key==='extra-'+id+'-duplicate'));
assert.equal(JSON.stringify(old),snapshot,'inserir peca nao altera o molde original');
const wider=M.parts({...rail,width:1200});
assert.equal(find(wider,'extra-'+id).w,1158,'regua cresce ao mudar largura da carcaca');
assert.equal(id,rail.assemblyPieces[0].id,'id estavel ao recalcular');
assert.equal(find(M.parts(rail),'extra-'+id).w,758,'original salvo sem alterações');
const cava=M.insertAssembly(rail,'cavaRail',0,{at:0.90,height:70});
const cavaPiece=find(M.parts(cava),'extra-'+cava.assemblyPieces[1].id);
assert.equal(cavaPiece.w,764);
assert.match(cavaPiece.notes,/USINAGEM/);
assert(M.parts(cava).warnings.some(x=>x.includes('não foi gerado automaticamente')));
assert.throws(()=>M.insertAssembly(rail,'cavaRail',0,{at:0.70,height:70}),/sobrepostas/);
assert.throws(()=>M.insertAssembly(old,'rail',0,{at:0.98,height:150}),/invade tampo/);
const removed=M.removeAssembly(cava,id);
assert.equal(removed.assemblyPieces.length,1);
assert.equal(M.parts(removed).parts.some(p=>p.key==='extra-'+id),false);
assert.throws(()=>M.removeAssembly(old,'not-here'),/não encontrada/);
const back=M.insertAssembly(old,'backPanel',0,{});
assert.equal(back.back,'none','fundo por vao substitui fundo continuo');
assert.equal(M.parts(back).parts.some(p=>p.key==='back'),false);
const backPart=find(M.parts(back),'extra-'+back.assemblyPieces[0].id);
assert.equal(backPart.thickness,6);
assert.equal(backPart.w,694);
assert.equal(backPart.h,764);
assert.throws(()=>M.insertAssembly(back,'backPanel',0,{}),/já tem um fundo/);
assert.throws(()=>M.parts({...back,back:'overlay'}),/Não coloque fundo individual/);
const doors=M.setDoorsInBay(old,0,2);
const doorPart=find(M.parts(doors),'bay-door-0');
assert.equal(doors.doorMode,'byBay');
assert.equal(doorPart.qty,2);
assert.equal(doorPart.h,378.5);
assert(!M.parts(doors).parts.some(p=>p.key==='front'),'porta por vao substitui e nao soma as portas globais');
assert(M.parts(doors).warnings.some(w=>w.includes('portas globais')));
assert.equal(M.parts(M.restoreGlobalDoors(doors)).parts.find(x=>x.key==='front').qty,2);
assert.throws(()=>M.setDoorsInBay({...old,width:350},0,8),/não cabem/);
const split=M.splitBay(old,0,.5);
const splitLayout=M.parts(split);
assert.equal(splitLayout.bays.length,2);
assert.equal(splitLayout.parts.filter(p=>p.key.startsWith('divider-')).length,1);
assert.equal(splitLayout.parts.filter(p=>p.key.startsWith('shelf-')).length,2,'prateleiras do modelo divididas por novo vao');
assert(Math.abs(splitLayout.bays[0].width-splitLayout.bays[1].width)<=0.1);
assert.throws(()=>M.splitBay(rail,0,.5),/Retire-as/);
assert.throws(()=>M.splitBay(doors,0,.5),/Retire-as/);
const unequal=M.customBays({...old,shelfCount:0},[300,null,null]);
const splitIndex=M.splitBay({...unequal,shelvesByBay:{2:2}},0,.5);
assert.equal(M.parts(splitIndex).bays.length,4);
assert.equal(splitIndex.shelvesByBay[3],2,'atributo dos vaos a direita remapeado');
assert.throws(()=>M.equalBays(rail,2),/Retire ou reorganize/);
assert.throws(()=>M.customBays(back,[null,null]),/Retire ou reorganize/);
const templ={id:'standard',version:1,spec:old};
const inA=M.instantiate(templ,100,200),inB=M.instantiate(templ,1200,200);
M.regenerate(inA,{...cava});
assert.equal(M.parts(inA.moduleSpec).parts.filter(p=>p.key.startsWith('extra-')).length,2);
assert.equal(inB.moduleSpec.assemblyPieces.length,0,'modulos em outros projetos independentes');
const project={rooms:[{id:'room',name:'Cozinha'}],labLayouts:{room:{items:[inA]}}};
const cut=M.groupedCutRows(project,'room');
assert(cut['MDF 18 mm · 18 mm'].some(p=>p.modulePartKey==='extra-'+id));
assert(cut['MDF 18 mm · 18 mm'].some(p=>p.notes.includes('USINAGEM')));
assert.equal(cut['MDF 6 mm · 6 mm'].length,1);
console.log('Oficina por vao: peças, portas, fundos, precisão, montagem e cortes OK.');
