'use strict';
const A=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<!doctype html><html><body><div id="arqueLab"></div></body></html>',{
 url:'https://appassets.arque.invalid/index.html',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document,base='app/src/main/assets/';
for(const file of ['modules.js','corner45.js','kitchen-catalog.js','construction-studio.js','lab-alignment.js','lab-precision.js','lab-advanced.js','lab-fabrication.js','lab-visual.js','workshop.js','module-ui.js','lab.js'])
 w.eval(fs.readFileSync(base+file,'utf8'));
const M=w.ArqueModules;
const first=M.instantiate({id:'base',spec:M.standard()},100,100);first.z=100;
const room={id:'r',name:'Cozinha em obra',measurements:[]},l={width:4100,depth:3000,height:2700,confirmed:true,roomRefs:{},items:[first],history:[],future:[]};
const p={rooms:[room],photos:[],labLayouts:{r:l}},state={moduleTemplates:[],profileTemplates:[],constructionFavorites:[]},toast=[];
w.ArqueLab.mount(p,{state,persist:()=>Promise.resolve(),toast:m=>toast.push(m),exportCutMaterial:()=>{}});
const click=(a,arg)=>{const el=[...d.querySelectorAll('[data-lab="'+a+'"]')].find(x=>arg===undefined||x.dataset.arg===arg);A(el,'Ação indisponível '+a+' '+arg);el.click();};
const search=(val)=>{const el=d.getElementById('studioCatalogSearch');A(el);el.value=val;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
A(d.querySelector('.studio-construction'),'ambiente da construção identificado');
A(d.querySelector('.studio-catalog'),'biblioteca na lateral');
A(d.querySelector('.studio-preset-results'),'catálogo com miniaturas presente');
A(d.querySelector('.studio-room-drawer:not([open])'),'dimensões recolhidas até solicitar');
A(d.querySelector('.studio-advanced-drawer:not([open])'),'ferramentas avançadas não cobrem o ambiente 3D');
A(d.querySelector('#labBoard.lab-visual'),'ambiente espacial visível desde entrada');
A(d.querySelector('.studio-inspector[hidden]'),'propriedades começam recolhidas');
A(d.querySelector('[data-lab="studioNav"][data-arg="orbit"]'),'orbitar na barra da câmera');
A(d.querySelector('[data-lab="studioFit"]'),'enquadrar o ambiente');
click('studioNav','orbit');
A(d.querySelector('[data-lab="studioNav"][data-arg="orbit"].lab-active'),'ferramenta órbita ativa');
const orbitStart=d.querySelector('#labBoard').outerHTML;
const pointer=(name,x,y,id=111)=>{
 const e=new w.Event(name,{bubbles:true,cancelable:true});
 Object.defineProperties(e,{pointerId:{value:id},isPrimary:{value:id===111},clientX:{value:x},clientY:{value:y}});
 d.querySelector('#labBoard').dispatchEvent(e);
};
pointer('pointerdown',300,220);
pointer('pointermove',480,155);
pointer('pointerup',480,155);
const rotated=d.querySelector('#labBoard').outerHTML;
A.notEqual(rotated,orbitStart,'arrastar em modo girar altera a perspectiva');
A(!rotated.includes('NaN'),'câmera mantém projeção válida');
click('studioNav','pan');
const beforePan=d.querySelector('#labBoard').outerHTML;
pointer('pointerdown',320,230);
pointer('pointermove',400,300);
pointer('pointerup',400,300);
const afterPan=d.querySelector('#labBoard').outerHTML;
A.notEqual(beforePan,afterPan,'pan desloca a vista, não o objeto');
A(afterPan.includes('studio-camera-world'),'agrupamento deslocável presente');
click('studioFit');
A(d.querySelector('#labBoard').outerHTML.includes('translate(0 0)'),'enquadrar recentraliza vista');
click('studioNav','orbit');
pointer('pointerdown',320,230);
pointer('pointerdown',500,230,222);
pointer('pointermove',600,230,222);
pointer('pointerup',600,230,222);
pointer('pointerup',320,230);
A(d.querySelector('.studio-cam-angle')?.textContent.includes('%'),'pinça de zoom reflete estado da câmera');
click('studioFit');
A.equal(l.items.length,1,'girar e aproximar não inserem nem movem módulos');

A(d.querySelector('[data-lab="catalogPreset"][data-arg="base-4drawers"]'),'gaveteiro real disponível');
const itemsCount=d.querySelectorAll('.studio-preset').length;
A(itemsCount>=8,'vários modelos de base disponíveis');
search('gaveteiro 4');A.equal(d.querySelectorAll('.studio-preset').length,1);
search('');A(d.querySelectorAll('.studio-preset').length>=itemsCount);
click('studioFavorite','base-4drawers');A.deepEqual(state.constructionFavorites,['base-4drawers']);
click('studioCategory','Favoritos');
A.equal(d.querySelectorAll('.studio-preset').length,1,'favorito isolado');
click('studioCategory','Inferiores');
click('catalogSelect',first.id);A(!d.querySelector('.studio-inspector[hidden]'),'toque na árvore abre o inspetor');
let side=d.querySelector('#studioInsertSide');side.value='right';side.dispatchEvent(new w.Event('change',{bubbles:true}));
click('catalogPreset','base-4drawers');
const drawer=l.items.find(i=>i.presetId==='base-4drawers');A(drawer,'gaveteiro realmente inserido');
A.equal(drawer.kind,'module');A.equal(drawer.x,903);A.equal(drawer.y,100);
A(drawer.moduleSpec.accessories[0].count===4,'gavetas são peças dimensionadas');
A(M.parts(drawer.moduleSpec).parts.some(part=>part.name.toLowerCase().includes('gaveta')));
A(d.querySelector('#labQuickMaterial'),'edição do MDF da caixa presente');
A(d.querySelector('#labBoard [data-lab-object="'+drawer.id+'"]'),'novo módulo na cena');
click('studioInspectorToggle');A(d.querySelector('.studio-inspector[hidden]'),'recolhe a inspeção ao clicar');
click('studioInspectorToggle');A(!d.querySelector('.studio-inspector[hidden]'),'propriedades reabrem sem perder seleção');
click('studioCategory','Cantos');
A(d.querySelector('[data-lab="catalogPreset"][data-arg="corner-pentagonal"]'),'canto pentagonal no catálogo');
click('studioCategory','Eletrodomésticos');
A(d.querySelector('[data-lab="catalogPreset"][data-arg="microwave"]'),'micro-ondas disponível');
click('studioCategory','Banheiros');
A(d.querySelector('[data-lab="catalogPreset"][data-arg="bath-vanity"]'),'módulos de banheiro');
click('studioCategory','Salas e painéis');
A(d.querySelector('[data-lab="catalogPreset"][data-arg="living-panel"]'),'painéis de sala');
A(d.querySelector('.studio-object-tree'),'lista de módulos da obra preservada');
A(d.querySelector('[data-lab="advCorner"]'),'construção em L mantida');
console.log('Modo construção: área 3D, 48 modelos, famílias, favoritos, busca, encaixe, S Pen e inspetor OK.');
