'use strict';
const A=require('node:assert/strict');
const S=require('../app/src/main/assets/construction-studio.js');
const M=require('../app/src/main/assets/modules.js');
const K=require('../app/src/main/assets/kitchen-catalog.js');
const C=require('../app/src/main/assets/corner45.js');
globalThis.ArqueModules=M;globalThis.ArqueCorner45=C;
const presets=S.templates(K.catalog(),[]);
A.equal(presets.length,48);
for(const group of ['Inferiores','Aéreos','Torres','Cantos','Bancadas','Eletrodomésticos','Iluminação','Banheiros','Salas e painéis','Favoritos'])
 A(S.categories.includes(group),group);
const base=S.catalogHTML(presets,'Inferiores','',[]);
A(base.includes('Balcão com 2 portas'));
A(base.includes('base-4drawers'));
A(!base.includes('Coifa · referência'),'separar famílias');
A(S.catalogHTML(presets,'Aéreos','Micro',[]).includes('Nicho de micro-ondas'));
A(!S.catalogHTML(presets,'Aéreos','Micro',[]).includes('Balcão com 2 portas'));
const favorite=S.catalogHTML(presets,'Favoritos','',['base-4drawers']);
A(favorite.includes('Gaveteiro 4 gavetas'));
A(!favorite.includes('Balcão com 2 portas'));
A(favorite.includes('★'));
A(S.catalogHTML(presets,'Todos','não existe',[]).includes('Nenhum módulo'));
A(S.sketch({kind:'module',doors:2}).includes('<svg'));
A(!S.catalogHTML([{id:'injected',action:'catalogPreset',arg:'injected',kind:'module',label:'<script>alert(1)</script>',group:'Inferiores',w:800,d:560,h:730}],'Inferiores','',[]).includes('<script>'),'catálogo escapa HTML do nome');
const first=M.instantiate({id:'mod1',spec:M.standard()},100,100);first.z=100;
const second=M.instantiate({id:'mod2',spec:M.standard()},10,100);second.z=100;
const room={width:3500,depth:2600,height:2600,items:[first]};
const p=S.proposed(room,second,first.id,'right',3);
A.equal(p.x,903);
A.equal(p.y,100);
A.equal(p.side,'right');
A(S.check(room,second,p.x,p.y));
const fallback=S.proposed(room,second,first.id,'left',3);A.equal(fallback.side,'right','sem espaço à esquerda, preferir outro encaixe válido');A(S.check(room,second,fallback.x,fallback.y));
A.throws(()=>S.proposed({...room,width:700},second,first.id,'right',3),/Não há espaço livre/);
const placed={...second,x:p.x,y:p.y};
A(!S.check({...room,items:[first,placed]},second,first.x,first.y),'evitar colisão física dos módulos');
const other=K.create('base-4drawers',M);
A.equal(other.moduleSpec.accessories[0].count,4);
A(M.parts(other.moduleSpec).parts.some(part=>/Gaveta|gaveta/.test(part.name)));
const corner=K.create('corner-pentagonal',M);
A.equal(corner.moduleSpec.corner45.enabled,true);
const tpl={id:'saved-1',name:'Meu gabinete',spec:M.standard()};
A.equal(S.templates([], [tpl])[0].action,'catalogSaved');
const view=S.resetCamera();
A.deepEqual(view,{angle:40,tilt:32,zoom:1,panX:0,panY:0});
const orbit=S.cameraDrag(view,'orbit',100,-50);
A.equal(orbit.angle,72);A.equal(orbit.tilt,43);A.deepEqual(view,S.resetCamera(),'não altera medidas nem vista original');
const moved=S.cameraDrag(view,'pan',200,-120);A.equal(moved.panX,200);A.equal(moved.panY,-120);
A.equal(S.cameraDrag(view,'zoom',0,-125).zoom,Math.E.toFixed?Math.min(3.5,Math.exp(1)):NaN);
A.equal(S.pinch(view,100,200).zoom,2);A.equal(S.pinch(view,100,50,20,10).zoom,.65);
A.equal(S.pinch({...view,zoom:3},100,200).zoom,3.5);
A.equal(S.cameraDrag(view,'orbit',2000,900).tilt,10);
A.throws(()=>S.cameraDrag(view,'invalido',1,2),/inválida/);
A.throws(()=>S.pinch(view,0,-100),/inválida/);
console.log('Studio de construção: 48 modelos, navegação orbital, pan, zoom, pinça e módulos seguros OK.');
