'use strict';
const assert=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js'),C=require('../app/src/main/assets/corner45.js');
const V=require('../app/src/main/assets/lab-visual.js'),Adv=require('../app/src/main/assets/lab-advanced.js'),F=require('../app/src/main/assets/lab-fabrication.js');
globalThis.ArqueModules=M;globalThis.ArqueCorner45=C;globalThis.ArqueFabrication=F;
const item=C.create(M),s=item.moduleSpec;
item.code='M07';
assert.equal(item.kind,'module');assert.equal(s.width,800);assert.equal(s.depth,800);assert.equal(s.corner45.chamfer,380);
const g=C.geometry(s);
assert.deepEqual(g.outline,[[0,0],[800,0],[800,420],[420,800],[0,800]]);
assert.equal(g.diagonalLength,537.4);
assert.equal(g.doorWidth,533.4);
assert.equal(g.area,567800);
assert.equal(g.inner.length,5);
assert(g.inner[2][0]<g.outline[2][0]&&g.inner[2][1]<g.outline[2][1]);
assert(Math.abs(g.inner[2][0]+g.inner[2][1]-(800+800-380-18*Math.SQRT2))<.15);
const p=M.parts(s);
assert.equal(p.nonRectangular,true);
assert.equal(p.parts.filter(x=>x.needsContour).reduce((a,b)=>a+b.qty,0),2);
assert(p.parts.find(x=>x.key==='corner-deck').outline.length===5);
assert(p.parts.some(x=>x.key==='corner-front'));
assert(p.warnings.some(x=>x.includes('CNC')));
const cut=M.cutRows(item,'Cozinha');
assert(cut.length>0);
assert(!cut.some(x=>x.requiresContour||x.modulePartKey==='corner-deck'));
assert(cut.some(x=>x.modulePartKey==='corner-front'),'porta entra na relação de retângulos para conferência');
const project={rooms:[{id:'r',name:'Cozinha'}],labLayouts:{r:{width:3600,depth:3000,height:2700,confirmed:true,items:[item]}}};
const grouped=M.groupedCutRows(project,'r');
const flat=Object.values(grouped).flat();
assert(flat.every(x=>!x.requiresContour),'otimizador recebe apenas painéis retangulares');
assert(!flat.some(x=>x.modulePartKey==='corner-deck'));
const report=Adv.production(project.labLayouts.r,M);
assert.equal(report.ready,false);
assert(report.lines.some(x=>x.shape==='polygon'&&x.cutStatus.includes('NÃO ENVIAR')));
assert(Adv.csv(report).includes('CONTORNO ESPECIAL'));
assert(Adv.csv(report).includes('"polygon"'));
assert(F.hardwareWarnings(item,M).some(x=>x.includes('diagonal')));
assert.throws(()=>F.hingePlan(item,{},M),/gabarito próprios/);
const result=V.scene(project.labLayouts.r,item.id,{mode:'fronts'});
assert(result.includes('data-lab-part="corner-front"'),'porta tocável em 3D');
assert(result.includes('45°'));
assert(result.includes('537,4'));
const open=V.scene(project.labLayouts.r,item.id,{mode:'structure'});
assert(open.includes('data-lab-part="corner-deck"'));
const modified=C.update(s,{chamfer:320,shelves:2},M);
assert.equal(modified.corner45.chamfer,320);
assert.equal(modified.corner45.shelves,2);
assert.equal(M.parts(modified).parts.filter(x=>x.needsContour).reduce((a,b)=>a+b.qty,0),4);
assert.equal(s.corner45.chamfer,380,'original preservado');
const noDoor=C.update(modified,{shelves:0},M);
const without=M.parts({...noDoor,doorCount:0});
assert(!without.parts.some(x=>x.key==='corner-front'));
assert.throws(()=>C.update(s,{chamfer:790},M),/Chanfro/);
assert.throws(()=>M.parts({...s,shelfCount:1}),/Divisórias retas/);
assert.throws(()=>M.parts({...s,back:'overlay'}),/fundo aplicado/);
assert.throws(()=>M.parts({...s,accessories:[{type:'drawer',bay:0,count:2,slideSide:12,frontClearance:20,rearClearance:20,height:100,slideLength:350}]}),/não se aplicam/);
const technical=C.svgTechnical(s);
assert(technical.startsWith('<svg')&&technical.includes('<polygon')&&technical.includes('45°'));
assert(!technical.includes('G1 X'),'SVG não inclui instruções CNC');
console.log('Canto pentagonal: cinco lados, cotas, prateleiras, porta, relatórios e isolamento CNC OK.');
