'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<!doctype html><html><body><div id="arqueLab"></div></body></html>',{
 url:'https://arque.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document,assets='app/src/main/assets/';
for(const file of ['modules.js','corner45.js','kitchen-catalog.js','lab-alignment.js','lab-precision.js','lab-advanced.js','lab-fabrication.js','lab-visual.js','workshop.js','module-ui.js','lab.js'])
 w.eval(fs.readFileSync(assets+file,'utf8'));
const project={rooms:[{id:'r',name:'Cozinha de canto',measurements:[]}],photos:[],labLayouts:{r:{width:3900,depth:3300,height:2600,confirmed:true,items:[],history:[],future:[],roomRefs:{}}}};
const notifications=[];
w.ArqueLab.mount(project,{state:{moduleTemplates:[],profileTemplates:[]},persist:()=>Promise.resolve(),toast:s=>notifications.push(s),exportCutMaterial:()=>{}});
const l=project.labLayouts.r;
const click=(action,arg)=>{const el=[...d.querySelectorAll('[data-lab="'+action+'"]')].find(el=>arg===undefined||el.dataset.arg===arg);assert(el,'não encontrou botão '+action+' '+arg);el.click();};
const set=(id,value)=>{const el=d.getElementById(id);assert(el,'não encontrou campo '+id);el.value=String(value);};
assert(d.querySelector('[data-lab="cornerCreate"]'),'catálogo do canto pentagonal');
click('cornerCreate');
const obj=l.items.find(x=>x.moduleSpec?.corner45?.enabled);
assert(obj,'módulo criado');
assert(/^M\d{2,}$/.test(obj.code),'código persistente');
assert(d.querySelector('#cornerChamfer'),'edição de chanfro');
assert(d.querySelector('.lab-corner-sketch svg'),'desenho técnico no inspetor');
assert(!d.querySelector('#modWorkbenchBay'),'editor retangular não aplicado indevidamente ao canto');
const prior=JSON.stringify(obj.moduleSpec),id=obj.id;
set('cornerChamfer','340');
set('cornerShelves','2');
set('cornerFillerLeft','30');
set('cornerDoor','1');
set('cornerMaterial','MDF Greige');
click('cornerUpdate');
const changed=l.items.find(x=>x.id===id);
assert.equal(changed.moduleSpec.corner45.chamfer,340);
assert.equal(changed.moduleSpec.corner45.shelves,2);
assert.equal(changed.moduleSpec.leftFiller,30);
assert.equal(changed.moduleSpec.caseMaterial,'MDF Greige');
assert.equal(changed.productionApproval,false);
const technical=w.ArqueModules.parts(changed.moduleSpec);
assert.equal(technical.parts.filter(x=>x.needsContour).reduce((a,p)=>a+p.qty,0),4);
assert(d.body.textContent.includes('Peças com cinco lados'),'alerta de contorno especial');
click('view','plan');
const poly=d.querySelector('#labBoard [data-lab-object="'+id+'"] polygon');
assert(poly,'canto pentagonal na planta');
assert(poly.getAttribute('points').split(' ').length===5,'exatamente cinco lados');
click('view','iso');
assert(d.querySelector('#labBoard [data-lab-object="'+id+'"] [data-lab-part="corner-front"]'),'porta diagonal selecionável');
click('undo');
assert.equal(l.items.find(x=>x.id===id).moduleSpec.corner45.chamfer,380,'desfazer restaura o chanfro');
click('redo');
assert.equal(l.items.find(x=>x.id===id).moduleSpec.corner45.chamfer,340,'refazer restaura geometria');
const partButtons=[...d.querySelectorAll('[data-lab="partSelect"]')];
assert(partButtons.some(x=>x.dataset.arg==='corner-deck'),'contorno pentagonal na árvore construtiva');
click('partSelect','corner-deck');
assert(d.body.textContent.includes('CONTORNO PENTAGONAL'),'peça mostra bloqueio de corte retangular');
const groups=w.ArqueModules.groupedCutRows(project,'r');
assert(!Object.values(groups).flat().some(x=>x.modulePartKey==='corner-deck'));
assert(!w.ArqueAdvanced.production(l,w.ArqueModules).ready);
assert(notifications.some(v=>v.includes('Contornos e peças')),'edição salvou');
console.log('Fase 9 UI: criar canto, editar chanfro e MDF, exibir planta/3D, desfazer/refazer e evitar corte indevido OK.');
