'use strict';
const A=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js');
const F=require('../app/src/main/assets/lab-fabrication.js');
const Adv=require('../app/src/main/assets/lab-advanced.js');
const V=require('../app/src/main/assets/lab-visual.js');
globalThis.ArqueModules=M;globalThis.ArqueFabrication=F;
const make=(id,x,y)=>{const it=M.instantiate({id,spec:M.standard()},x,y);it.code=id;it.z=100;return it;};
const back=make('M01',596,0),side=make('M02',0,0);
side.rotation=90;
const room={width:3600,depth:2800,height:2600,confirmed:true,cornerGuides:[],items:[back,side]};
const guide=F.create45(room,back.id,side.id,{reach:400,clearance:15});
A.equal(guide.angle,45);A.equal(guide.diagonalLength,565.7);
A.equal(guide.verified,false);
A.deepEqual(guide.start,[581,981]);A.deepEqual(guide.end,[981,581]);
A(!JSON.stringify(room).includes('corner45'),'guias não devem ser instalados sem confirmação');
const placed={...room,cornerGuides:[guide]};
A(V.scene(placed).includes('45° · 565.7 mm'),'frente diagonal na representação espacial');
const report=Adv.production(placed,M);
A(report.warnings.some(x=>x.includes('carcaça')),'canto visual bloqueia fabricação automática');
A.equal(report.ready,false);
A.throws(()=>F.create45(room,back.id,back.id),/diferentes/);
A.throws(()=>F.create45({...room,width:700},back.id,side.id,{reach:400}),/ultrapassa/);
A.throws(()=>F.create45(room,back.id,side.id,{reach:20}),/entre/);
const interfering=make('M03',700,600);
A.throws(()=>F.create45({...room,items:[back,side,interfering]},back.id,side.id,{reach:400}),/atravessa/);
const doors=F.hingePlan(back,{brand:'Ferragem da obra',model:'H35',diameter:35,edgeDistance:22,top:100,bottom:100,count:2},M);
A.equal(doors.doorLeaves,2);
A.equal(doors.holes.length,4);
A.equal(doors.holes[0].y,100);
A.equal(doors.holes[1].y,626);
A.equal(doors.holes[0].diameter,35);
A.equal(doors.verified,false);
A.equal(F.hingesStale(back,doors,M),false);
A.equal(F.hingesStale({...back,moduleSpec:{...back.moduleSpec,width:900}},doors,M),true);
A(F.hardwareWarnings(back,M).some(x=>x.includes('Falta plano')));
back.hingePlan=doors;
A(F.hardwareWarnings(back,M).some(x=>x.includes('não conferidas')));
A(F.hardwareCsv([back]).includes('M01'));
const doorless=make('M04',100,1200);doorless.moduleSpec=M.check({...doorless.moduleSpec,doorCount:0});
A.throws(()=>F.hingePlan(doorless,{},M),/não possui portas/);
A.throws(()=>F.hingePlan({...back,moduleSpec:{...back.moduleSpec,doorCount:8}},{diameter:45,edgeDistance:90,top:250,bottom:250,count:6},M),/Porta/);
const drawer=make('M05',1100,1200);
drawer.moduleSpec=M.check({...drawer.moduleSpec,accessories:[{type:'drawer',bay:0,count:3,slideSide:12.7,frontClearance:20,rearClearance:20,height:150,slideLength:400}]});
const slides=F.slidesPlan(drawer,{brand:'Ferragem real',model:'Guia 400',side:13,length:400,front:20,rear:25},M);
A.equal(slides.spec.accessories[0].slideSide,13);
A.equal(slides.spec.accessories[0].rearClearance,25);
A.equal(slides.configuration.drawerCount,3);
A.equal(drawer.moduleSpec.accessories[0].slideSide,12.7,'não alterar original antes de salvar');
A.throws(()=>F.slidesPlan(drawer,{side:13,length:850,front:20,rear:25},M),/Comprimento da corrediça/);
A.throws(()=>F.slidesPlan(doorless,{},M),/Adicione gavetas/);
drawer.slideConfiguration=slides.configuration;
A(F.hardwareWarnings(drawer,M).some(x=>x.includes('não conferidas')));
console.log('Etapa 8: canto 45 visual, desenho espacial, dobradiças, corrediças e bloqueio CNC OK.');
