/* Motor paramétrico: estrutura, vão, divisórias, reutilização, prevenção de erros. */
'use strict';
const A=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js');
const model=M.standard();
A.equal(model.width,800);
const base=M.parts(model);
const find=(list,k)=>list.find(x=>x.key===k);
A.equal(find(base.parts,'side').w,730);
A.equal(find(base.parts,'side').h,560);
A.equal(find(base.parts,'side').qty,2);
A.equal(find(base.parts,'topbottom').w,764);
A.equal(find(base.parts,'topbottom').qty,2);
A.equal(find(base.parts,'front').w,726);
A.equal(find(base.parts,'front').h,396.5);
A.equal(find(base.parts,'front').qty,2);
A.equal(find(base.parts,'shelf-0-0').w,760);
A.equal(find(base.parts,'shelf-0-0').h,540);
A.equal(find(base.parts,'back').thickness,6);
A.equal(base.installedDepth,566);
const s=M.addDivider(model,0.5);
const withMiddle=M.parts(s);
A.equal(withMiddle.bays.length,2);
A.equal(find(withMiddle.parts,'divider-0').w,694);
A.equal(find(withMiddle.parts,'shelf-0-0').w,369);
A.equal(find(withMiddle.parts,'shelf-0-1').w,369);
A.throws(()=>M.parts({...s,vertical:[0.49,0.51]}),/próximas|vão menor/);
A.throws(()=>M.parts({...s,width:200}),/insuficiente|Divisórias/);
A.throws(()=>M.parts({...s,shelfCount:9}),/Prateleiras demais/);
A.throws(()=>M.parts({...s,doorGap:999}),/Folga/);
A.equal(M.parts({...model,leftFiller:30,rightFiller:30}).installedWidth,860);
const state={moduleTemplates:[]};
const saved=M.saveTemplate(state,s,'Base duas portas com divisória');
const savedSnapshot=JSON.stringify(saved.spec);
const inA=M.instantiate(saved,100,200),inB=M.instantiate(saved,700,200);
const result=M.regenerate(inA,{width:1200,height:800});
A.equal(inA.w,1200);A.equal(inA.height,800);
A.equal(find(result.parts,'topbottom').w,1164);
A.equal(find(result.parts,'divider-0').w,764);
A.equal(inB.w,800,'alterar instância não altera cópia');
A.equal(JSON.stringify(saved.spec),savedSnapshot,'alterar instância não altera biblioteca');
const project={rooms:[{id:'cozinha',name:'Cozinha'},{id:'sala',name:'Sala'}],labLayouts:{
 cozinha:{items:[inA,inB]},sala:{items:[]}
}};
const groups=M.groupedCutRows(project,'cozinha');
A(groups['MDF 18 mm · 18 mm']);
A(groups['MDF 6 mm · 6 mm']);
A.equal(groups['MDF 6 mm · 6 mm'].length,2);
A.equal(groups['MDF 18 mm · 18 mm'].every(x=>x.thickness===18),true);
A.equal(groups['MDF 18 mm · 18 mm'].every(x=>x.material==='MDF 18 mm'),true);
A.equal(groups['MDF 18 mm · 18 mm'][0].sourceRoomId,'cozinha');
A.equal(groups['MDF 18 mm · 18 mm'][0].generated,true);
A.notEqual(groups['MDF 18 mm · 18 mm'][0].id,groups['MDF 18 mm · 18 mm'][6].id);
const old=JSON.stringify(project);
A.equal(M.groupedCutRows(project,'sala')['MDF 18 mm · 18 mm'],undefined);
A.equal(JSON.stringify(project),old,'geração de peças não altera as medidas de projeto');
// Novos métodos de montagem e folgas registradas pelo profissional.
const over=M.parts({...model,construction:'over'});
A.equal(find(over.parts,'side').w,694);
A.equal(find(over.parts,'topbottom').w,800);
A.equal(find(M.parts({...model,doorTopDiscount:12,doorBottomDiscount:6}).parts,'front').w,708);
const fixed=M.parts({...model,fixedShelves:[{bay:0,at:0.5}]});
A.equal(find(fixed.parts,'fixed-0').w,760);
A.equal(fixed.parts.some(x=>x.key==='shelf-0-0'),false,'prateleira solta substituída pela fixa no mesmo plano');
A.throws(()=>M.parts({...model,fixedShelves:[{bay:0,at:0.5},{bay:0,at:0.501}]}),/sobrepostas/);
A.throws(()=>M.parts({...model,fixedShelves:[{bay:2,at:0.5}]}),/inexistente/);
const drawer=M.parts({...model,accessories:[{
 type:'drawer',bay:0,count:1,slideSide:12.5,rearClearance:20,frontClearance:10,height:140,slideLength:500
}]});
A.equal(find(drawer.parts,'acc-0-sides').w,530);
A.equal(find(drawer.parts,'acc-0-sides').qty,2);
A.equal(find(drawer.parts,'acc-0-ends').w,703);
A.equal(find(drawer.parts,'acc-0-bottom').w,739);
A.equal(find(drawer.parts,'acc-0-bottom').thickness,6);
const tempero=M.parts({...model,accessories:[{
 type:'spice',bay:0,count:2,slideSide:10,rearClearance:15,frontClearance:10,height:120,slideLength:450
}]});
A.equal(find(tempero.parts,'acc-0-sides').qty,4);
A.match(find(tempero.parts,'acc-0-bottom').name,/Porta-temperos/);
A.throws(()=>M.parts({...model,accessories:[{type:'drawer',bay:0,count:1,slideSide:12.5,rearClearance:20,frontClearance:10,height:140,slideLength:700}]}),/corrediça maior/);
A.throws(()=>M.parts({...model,accessories:[{type:'drawer',bay:0,count:6,slideSide:12.5,rearClearance:20,frontClearance:10,height:220,slideLength:500}]}),/ultrapassam/);
A.equal(M.saveTemplate(state,{...model,construction:'over',fixedShelves:[{bay:0,at:0.5}]},'Base com tampo sobreposto').spec.fixedShelves.length,1);
// Perfis livres só são referências geométricas: não entram em corte nem CNC.
const W=require('../app/src/main/assets/workshop.js');
const profileState={};
const original={kind:'pen',points:[[12,20],[112,20],[112,70]]};
const prof=W.saveProfile(profileState,original,'Moldura lisa personalizada');
A.equal(prof.width,100);A.equal(prof.height,50);
A.equal(prof.manufacturable,false);
A.equal(original.points[0][0],12,'traçado original preservado');
const instProf=W.insertProfile(prof,300,150,'front');
A.equal(instProf.w,100);A.equal(instProf.d,50);
instProf.w=140;
A.equal(prof.width,100,'salvar um perfil não muda o molde base');
A.throws(()=>W.saveProfile(profileState,{kind:'pen',points:[[0,0],[1,1]]},'Pequena'),/pequena/);
const fitted=W.fit({...model,leftFiller:30,rightFiller:30},1000,5,5,M);
A.equal(fitted.spec.width,930);
A.equal(fitted.installed,990);
A.equal(fitted.remaining,10);
A.throws(()=>W.fit(model,200,80,80,M),/insuficiente/);
const sampleLayout={width:1200,depth:850,height:2600,confirmed:true,items:[{...M.instantiate({id:'tmp',spec:model},0,0),x:30,y:30}]};
A.equal(W.roomAudit(sampleLayout).errors.length,0);
sampleLayout.items.push({...M.instantiate({id:'tmp',spec:model},200,100)});
A(W.roomAudit(sampleLayout).errors.some(x=>x.code==='OVERLAP'));
sampleLayout.items.pop();
sampleLayout.items[0].x=500;
A(W.roomAudit(sampleLayout).errors.some(x=>x.code==='OUTSIDE'));
sampleLayout.confirmed=false;
A(W.roomAudit(sampleLayout).warnings.some(x=>x.code==='UNCONFIRMED'));
const panel={id:'painel-avulso',kind:'panel',label:'Tampo avulso',w:780,d:560,material:'MDF 18 mm',thickness:18,grain:true,edge2:1,edge04:0};
project.labLayouts.cozinha.items.push(panel);
const panels=M.groupedCutRows(project,'cozinha')['MDF 18 mm · 18 mm'];
const avulso=panels.find(x=>x.id==='panel-painel-avulso');
A(avulso,'Peça avulsa retangular enviada a lote apropriado');
A.equal(avulso.name,'Cozinha · Tampo avulso');
A.equal(avulso.w,780);A.equal(avulso.h,560);
A.equal(avulso.grain,true);A.equal(avulso.sourceRoomId,'cozinha');
panel.material='MDF 25 mm';panel.thickness=25;
A(M.groupedCutRows(project,'cozinha')['MDF 25 mm · 25 mm'][0].sourcePanelId==='painel-avulso');
panel.w=10;
A.throws(()=>M.groupedCutRows(project,'cozinha'),/inválido/);
console.log('Motor de módulos: montagem, corrediças, molduras e peças avulsas no corte OK.');
