/* Motor paramétrico: estrutura, vão, divisórias, reutilização, prevenção de erros. */
'use strict';
const A=require('node:assert/strict');
const M=require('../app/src/main/assets/modules.js');
const model=M.standard();
A.equal(model.width,800);
const base=M.parts(model);
const find=(list,k)=>list.find(x=>x.key===k);
A.equal(find(base.parts,'side').w,730);
A.equal(find(base.parts,'side').h,560);
A.equal(find(base.parts,'side').qty,2);
A.equal(find(base.parts,'topbottom').w,764);
A.equal(find(base.parts,'topbottom').qty,2);
A.equal(find(base.parts,'front').w,726);
A.equal(find(base.parts,'front').h,396.5);
A.equal(find(base.parts,'front').qty,2);
A.equal(find(base.parts,'shelf-0-0').w,760);
A.equal(find(base.parts,'shelf-0-0').h,540);
A.equal(find(base.parts,'back').thickness,6);
A.equal(base.installedDepth,566);
const s=M.addDivider(model,0.5);
const withMiddle=M.parts(s);
A.equal(withMiddle.bays.length,2);
A.equal(find(withMiddle.parts,'divider-0').w,694);
A.equal(find(withMiddle.parts,'shelf-0-0').w,369);
A.equal(find(withMiddle.parts,'shelf-0-1').w,369);
A.throws(()=>M.parts({...s,vertical:[0.49,0.51]}),/próximas|vão menor/);
A.throws(()=>M.parts({...s,width:200}),/insuficiente|Divisórias/);
A.throws(()=>M.parts({...s,shelfCount:9}),/Prateleiras demais/);
A.throws(()=>M.parts({...s,doorGap:999}),/Folga/);
A.equal(M.parts({...model,leftFiller:30,rightFiller:30}).installedWidth,860);
const state={moduleTemplates:[]};
const saved=M.saveTemplate(state,s,'Base duas portas com divisória');
const savedSnapshot=JSON.stringify(saved.spec);
const inA=M.instantiate(saved,100,200),inB=M.instantiate(saved,700,200);
const result=M.regenerate(inA,{width:1200,height:800});
A.equal(inA.w,1200);A.equal(inA.height,800);
A.equal(find(result.parts,'topbottom').w,1164);
A.equal(find(result.parts,'divider-0').w,764);
A.equal(inB.w,800,'alterar instância não altera cópia');
A.equal(JSON.stringify(saved.spec),savedSnapshot,'alterar instância não altera biblioteca');
const project={rooms:[{id:'cozinha',name:'Cozinha'},{id:'sala',name:'Sala'}],labLayouts:{
 cozinha:{items:[inA,inB]},sala:{items:[]}
}};
const groups=M.groupedCutRows(project,'cozinha');
A(groups['MDF 18 mm · 18 mm']);
A(groups['MDF 6 mm · 6 mm']);
A.equal(groups['MDF 6 mm · 6 mm'].length,2);
A.equal(groups['MDF 18 mm · 18 mm'].every(x=>x.thickness===18),true);
A.equal(groups['MDF 18 mm · 18 mm'].every(x=>x.material==='MDF 18 mm'),true);
A.equal(groups['MDF 18 mm · 18 mm'][0].sourceRoomId,'cozinha');
A.equal(groups['MDF 18 mm · 18 mm'][0].generated,true);
A.notEqual(groups['MDF 18 mm · 18 mm'][0].id,groups['MDF 18 mm · 18 mm'][6].id);
const old=JSON.stringify(project);
A.equal(M.groupedCutRows(project,'sala')['MDF 18 mm · 18 mm'],undefined);
A.equal(JSON.stringify(project),old,'geração de peças não altera as medidas de projeto');
console.log('Motor de módulos: dimensões, divisórias, reuso e grupos por material OK.');
