'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const base='app/src/main/assets/';
const dom=new JSDOM('<!doctype html><html><body><div id="arqueLab"></div></body></html>',{
 url:'https://arque.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,doc=w.document;
for(const name of ['modules.js','kitchen-catalog.js','lab-alignment.js','lab-precision.js','lab-advanced.js','lab-visual.js','workshop.js','module-ui.js','lab.js'])
 w.eval(fs.readFileSync(base+name,'utf8'));
const M=w.ArqueModules;
const spec=M.check({...M.standard(),doorCount:0,shelfCount:0,assemblyPieces:[{id:'detail',type:'rail',bay:0,at:.5,height:70,widthClearance:0,frontInset:0,rearInset:0,label:'Travessa'}]});
const a=M.instantiate({id:'test',spec},100,100);a.z=100;
const b=M.instantiate({id:'other',spec:M.standard()},1400,100);b.z=100;
const l={width:3500,depth:2600,height:2500,confirmed:true,roomRefs:{},items:[a,b],history:[],future:[],photoId:''};
const p={rooms:[{id:'r',name:'Cozinha',measurements:[]}],photos:[],labLayouts:{r:l}};
const toast=[];
w.ArqueLab.mount(p,{state:{moduleTemplates:[],profileTemplates:[]},persist:()=>Promise.resolve(),toast:s=>toast.push(s),exportCutMaterial:()=>{}});
const click=(action,arg)=>{const btn=[...doc.querySelectorAll('[data-lab="'+action+'"]')].find(b=>arg===undefined||b.dataset.arg===arg);assert(btn,'botão '+action+' '+arg+' ausente');btn.click();};
const tap=elem=>{
 const ev=new w.Event('pointerdown',{bubbles:true,cancelable:true});
 Object.defineProperties(ev,{pointerId:{value:101},isPrimary:{value:true},clientX:{value:190},clientY:{value:190}});
 elem.dispatchEvent(ev);
};
assert(doc.querySelector('#labBoard.lab-visual'),'laboratório inicia espacial');
assert(doc.querySelector('[data-lab="precisionToggle"]'),'visibilidade de cotas acessível');
click('visualMode','structure');
const group=doc.querySelector('#labBoard [data-lab-object="'+a.id+'"]');
assert(group,'modelo na cena');
const piece=group.querySelector('[data-lab-part="extra-detail"]');
assert(piece,'travessa selecionável pelo desenho');
tap(piece);
assert(doc.querySelector('.lab-selected-part')?.textContent.includes('Travessa'),'toque abre ficha técnica específica');
assert(doc.querySelector('#advPartHeight'),'toque oferece edição da peça');
assert(doc.querySelector('.lab-precision-panel')?.textContent.includes('Esquerda'),'cotas de paredes na ficha do objeto');
let step=doc.querySelector('#labPrecisionStep');assert(step,'precisão controlada');
step.value='5';
click('precisionMove','x:+');
assert.equal(l.items.find(i=>i.id===a.id).x,105,'mover eixo X em cinco milímetros');
click('undo');
assert.equal(l.items.find(i=>i.id===a.id).x,100,'desfazer movimento numérico');
click('redo');
assert.equal(l.items.find(i=>i.id===a.id).x,105,'refazer movimento numérico');
click('precisionToggle');
const board=doc.querySelector('#labBoard');
assert(!board.outerHTML.includes('L 800 mm'),'cotas desaparecem quando desativadas');
click('precisionToggle');
assert(doc.querySelector('#labBoard').outerHTML.includes('L 800 mm'),'cotas aparecem novamente');
const current=doc.querySelector('[data-lab-prop="x"]').value;
click('precisionMove','x:+');assert.notEqual(doc.querySelector('[data-lab-prop="x"]').value,current);
assert(toast.some(x=>x.includes('Posição X')),'aviso confirma posição numérica');
console.log('Etapa 7 UI: seleção peça física, ficha técnica, cotas e movimentação precisa OK.');
