'use strict';
const assert=require('node:assert/strict'),M=require('../app/src/main/assets/modules.js'),P=require('../app/src/main/assets/lab-precision.js'),V=require('../app/src/main/assets/lab-visual.js');
globalThis.ArqueModules=M;globalThis.ArquePrecision=P;
const a=M.instantiate({id:'m',spec:M.standard()},100,100);a.z=100;a.code='M01';
const b=M.instantiate({id:'m2',spec:M.standard()},1500,100);b.z=100;b.code='M02';
const l={width:3500,depth:2700,height:2650,confirmed:true,items:[a,b]};
const f=P.footprint(a);assert.equal(f.w,800);assert.equal(f.d,566);
const m=P.metrics(l,a.id);assert.equal(m.left,100);assert.equal(m.right,2600);
assert.equal(m.back,100);assert.equal(m.front,2034);assert.equal(m.top,1820);
assert.equal(m.w,800);assert.equal(m.d,566);
const before=JSON.stringify(l);
const next=P.nudge(l,a.id,'x',5);assert.equal(next.x,105);assert.equal(next.y,100);
assert.equal(JSON.stringify(l),before,'prévia do movimento não altera projeto');
assert.equal(P.nudge(l,a.id,'z',5).z,105);
assert.equal(P.nudge(l,a.id,'y',-5).y,95);
assert.throws(()=>P.nudge(l,a.id,'z',2000),/Deslocamento|limites/);
assert.throws(()=>P.nudge(l,a.id,'x',-500),/limites/);
assert.throws(()=>P.nudge(l,a.id,'x',650),/invadir/,'um móvel não pode invadir outro');
assert.throws(()=>P.nudge(l,a.id,'y',0),/Deslocamento/);
assert.throws(()=>P.nudge(l,a.id,'bad',5),/eixo/);
assert.equal(P.clearances(l,a.id).find(x=>x.id===b.id&&x.axis==='x').gap,600);
const rotated={...a,rotation:90},R=P.footprint(rotated);
assert.equal(R.w,566);assert.equal(R.d,800);
const upper={...M.instantiate({id:'upper',spec:{...M.standard(),depth:350,height:700}},100,100),z:1400};
assert.doesNotThrow(()=>P.nudge({...l,items:[a,upper]},a.id,'x',5),'aéreo acima não impede nudge do inferior');
const s=M.check({...M.standard(),doorCount:0,shelfCount:2,vertical:[0.5],assemblyPieces:[{id:'railtest',type:'rail',bay:0,at:.6,height:65,widthClearance:0,frontInset:0,rearInset:0,label:'Travessa teste'}]});
const obj=M.instantiate({id:'test',spec:s},200,100);obj.z=100;obj.code='M03';
const room={width:3000,depth:2600,height:2500,confirmed:true,items:[obj]};
const structure=V.scene(room,obj.id,{mode:'structure',showDimensions:true,partKey:'extra-railtest'});
assert(structure.includes('data-lab-part="side"'));
assert(structure.includes('data-lab-part="divider-0"'));
assert(structure.includes('data-lab-part="shelf-0-0"'));
assert(structure.includes('data-lab-part="extra-railtest"'));
assert(structure.includes('L 800 mm')&&structure.includes('P 566 mm'));
assert(structure.includes('fill-opacity=".5"'),'peça selecionada destacada');
const front=V.scene(room,obj.id,{mode:'fronts',showDimensions:false});
assert(!front.includes('data-lab-part="divider-0"'),'clicar peças físicas acontece no modo estrutura');
assert(!front.includes('L 800 mm'),'cotas desligadas não poluem o ambiente');
assert.equal(JSON.stringify(room),JSON.stringify(room),'render não altera estado');
console.log('Etapa 7: cotas, folgas, rotação, movimentos seguros e seleção 3D de peças OK.');
