'use strict';
const assert=require('node:assert/strict');
const V=require('../app/src/main/assets/lab-visual.js');
const M=require('../app/src/main/assets/modules.js');
globalThis.ArqueModules=M;
const Workshop=require('../app/src/main/assets/workshop.js');
const base=M.instantiate({id:'base',version:1,spec:{...M.standard(),name:'Base Greige'}},100,60);
base.z=100;const upper=M.instantiate({id:'upper',version:1,spec:{...M.standard(),name:'Aereo Greige',height:700,depth:350}},100,60);
upper.z=1700;
const room={width:3200,depth:2400,height:2600,confirmed:true,items:[base,upper]};
assert.equal(Workshop.roomAudit(room).errors.length,0,'armário superior e inferior sobrepostos na planta não colidem em 3D');
const L=require('../app/src/main/assets/lab.js');
const persistProject={rooms:[{id:'coz',name:'Cozinha'}],labLayouts:{coz:{width:3200,depth:2400,height:2600,confirmed:true,items:[base,upper],history:[],future:[],roomRefs:{}}}};
const live=L.layout(persistProject,'coz');
assert.equal(live.items[0].code,'M01');
assert.equal(live.items[1].code,'M02');
const stable=live.items[1].code;
live.items.splice(0,1);
L.ensureModuleCodes(live);
assert.equal(live.items[0].code,stable,'módulo não renumera após excluir outro');
const third=M.instantiate({id:'tower',version:1,spec:M.standard()},700,100);
live.items.push(third);L.ensureModuleCodes(live);
assert.equal(third.code,'M03','módulo novo recebe código nunca utilizado pelo anterior');
const cut=M.cutRows(third,'Cozinha');
assert.equal(cut[0].pieceCode,'M03-P01');
assert(cut[0].notes.includes('Identificação M03-P01'),'peça identificada na produção');
assert.equal(V.catalog(room).length,2);
assert.equal(V.catalog(room)[0].code,'M01');assert.equal(V.catalog(room)[1].code,'M02');
assert.equal(V.catalog(room)[1].z,1700,'altura de instalação numérica');
const html=V.scene(room,base.id,{angle:40,mode:'fronts'});
assert(html.includes('viewBox="0 0 1000 650"'),'prancheta SVG');
assert(html.includes('data-lab-object="'+base.id+'"'),'módulo selecionável');
assert(html.includes('data-lab-code="M01"'),'identificador técnico visível');
assert(html.includes('3.200 × 2.400 × 2.600 mm'),'dimensão real do ambiente');
assert(html.includes('MEDIDAS CONFIRMADAS'),'diferenciar medidas verificadas');
assert(html.includes('lab-selected'),'seleção destacada');
assert(html.includes('Ambiente técnico 3D'),'acessibilidade da cena');
assert(html.includes('polygon'),'paredes, piso e móveis com geometria real');
const structure=V.scene(room,upper.id,{angle:40,mode:'structure'});
assert(structure.includes('data-lab-object="'+upper.id+'"'));
assert(!structure.includes('RASCUNHO NÃO CONFERIDO'));
assert.notEqual(structure,html,'carcaça aberta não pode ser apenas a mesma frente');
const rotated=V.scene(room,base.id,{angle:90,mode:'fronts'});
assert.notEqual(rotated,html,'camera orbita sem alterar peças');
const camera=V.camera(room,{angle:40,zoom:1}),zoomed=V.camera(room,{angle:40,zoom:1.8});
const dist=c=>{const a=c.project(0,0,0),b=c.project(1000,0,0);return Math.hypot(a[0]-b[0],a[1]-b[1]);};
assert(zoomed.scale>camera.scale);assert(dist(zoomed)>dist(camera));
const unchanged=JSON.stringify(room);V.scene(room,base.id,{angle:140,mode:'structure'});
assert.equal(JSON.stringify(room),unchanged,'visualização nunca altera medição e arquivo de projeto');
const standalone=V.scene({...room,confirmed:false},base.id,{});
assert(standalone.includes('RASCUNHO NÃO CONFERIDO'),'ambiente simulado não passa por medido automaticamente');
const older={...base,code:'COZ-019'};
assert.equal(V.identifier(older,0),'COZ-019','códigos explícitos são respeitados');
assert.equal(V.finishColor('MDF Grafite')[0],'#515961');
const evil={...base,id:'<svg/onload=evil()>',label:'<script>alert(1)</script>'};
const unsafe=V.scene({...room,items:[evil]},evil.id,{});
assert(!unsafe.includes('data-lab-object="<svg'),'IDs SVG são escapados');
assert(!unsafe.includes('<script>alert(1)</script>'),'nomes escapados');
upper.z=2100;
assert(Workshop.roomAudit(room).errors.some(x=>x.code==='HEIGHT'),'aéreo ultrapassando teto é bloqueado na auditoria');
upper.z=700;
assert(Workshop.roomAudit(room).errors.some(x=>x.code==='OVERLAP'),'armários em volumes físicos sobrepostos são detectados');
const Fridge={id:'f-1',kind:'fridge',label:'Geladeira teste',x:1200,y:800,z:0,w:760,d:720,height:1850,view:'plan'};
const Cooktop={id:'c-1',kind:'cooktop',label:'Cooktop teste',x:1250,y:60,z:900,w:600,d:510,height:45,view:'plan'};
const Leds={id:'led-1',kind:'led',label:'LED teste',x:100,y:60,z:1600,w:900,d:25,height:12,view:'plan'};
const staging={...room,items:[...room.items,Fridge,Cooktop,Leds]};
const stageSvg=V.scene(staging,Fridge.id,{mode:'fronts'});
assert(stageSvg.includes('data-lab-object="f-1"'));
assert(stageSvg.includes('data-lab-object="c-1"'));
assert(stageSvg.includes('data-lab-object="led-1"'));
assert(!stageSvg.includes('NaN'),'geometria de eletros preserva projeção');
assert.equal(V.catalog(staging).length,5,'catalogo inclui referências de montagem e iluminação');
console.log('Ambiente visual: modulação, três dimensões, câmera, estrutura, IDs e auditoria 3D OK.');
